"""Backend-agnostic verification problem IR."""

from engine.verification.capabilities import (
    CANDIDATE_KINDS,
    DYNAMICS_KINDS,
    MALFORMED_OBLIGATION_TARGETS,
    OBLIGATION_SHAPE_FEATURES,
    OBLIGATION_TARGETS,
    AdapterCapabilities,
    CapabilityAssessment,
    ObligationClassification,
    classifications_by_obligation,
    obligation_classifications,
)
from engine.verification.inspection_adapter import (
    ADAPTER_NAME,
    ADAPTER_CAPABILITIES,
    ARTIFACT_INSPECTION_OUTCOME_JSON,
    ARTIFACT_PROBLEM_JSON,
    ARTIFACT_REPORT_MARKDOWN,
    InspectionAdapterReport,
    InspectionArtifact,
    INSPECTION_ARTIFACT_KINDS,
    REPORT_STATUS,
    inspection_diagnostics,
    render_inspection_markdown,
    validate_inspection_artifact_index,
    write_inspection_artifacts,
)
from engine.verification.diagnostics import (
    DIAGNOSTIC_SEVERITIES,
    DIAGNOSTIC_STATUSES,
    VerificationDiagnostic,
)
from engine.verification.ir import (
    AssumptionSpec,
    CandidateSpec,
    DynamicsSpec,
    ExpressionSpec,
    InputSpec,
    ObligationSpec,
    ParameterSpec,
    ProofStatusSpec,
    RegionSpec,
    RegionGeometrySpec,
    SCHEMA_VERSION,
    VariableSpec,
    VerificationProblem,
)
from engine.verification.measured import (
    CertificateTrajectoryDiagnostics,
    certificate_series_for_trajectory,
    sampled_region_proof_statuses,
)
from engine.verification.region_geometry import (
    scalar_field_region_geometries,
    scalar_field_region_geometry,
)
from engine.verification.safety_adapter import (
    verification_problem_from_barrier,
    verification_problem_from_controlled_discrete_barrier,
    verification_problem_from_controlled_discrete_lyapunov,
    verification_problem_from_discrete_barrier,
    verification_problem_from_discrete_lyapunov,
    verification_problem_from_lyapunov,
    verification_problem_from_obligations,
)
from engine.verification.sympy_codec import expression_spec
from engine.verification.system_codec import (
    dynamics_spec_from_controlled,
    dynamics_spec_from_controlled_discrete,
    dynamics_spec_from_discrete,
    dynamics_spec_from_system,
)
from engine.verification.target_requirements import (
    SOS_POLYNOMIAL_ADAPTER,
    PolynomialRequirementReport,
    sos_polynomial_requirement_diagnostics,
)

__all__ = [
    "ADAPTER_NAME",
    "ADAPTER_CAPABILITIES",
    "ARTIFACT_INSPECTION_OUTCOME_JSON",
    "ARTIFACT_PROBLEM_JSON",
    "ARTIFACT_REPORT_MARKDOWN",
    "AdapterCapabilities",
    "AssumptionSpec",
    "CANDIDATE_KINDS",
    "CandidateSpec",
    "CapabilityAssessment",
    "DIAGNOSTIC_SEVERITIES",
    "DIAGNOSTIC_STATUSES",
    "DYNAMICS_KINDS",
    "DynamicsSpec",
    "ExpressionSpec",
    "InputSpec",
    "InspectionAdapterReport",
    "InspectionArtifact",
    "INSPECTION_ARTIFACT_KINDS",
    "MALFORMED_OBLIGATION_TARGETS",
    "OBLIGATION_SHAPE_FEATURES",
    "OBLIGATION_TARGETS",
    "ObligationClassification",
    "ObligationSpec",
    "ParameterSpec",
    "ProofStatusSpec",
    "REPORT_STATUS",
    "RegionGeometrySpec",
    "RegionSpec",
    "SCHEMA_VERSION",
    "SOS_POLYNOMIAL_ADAPTER",
    "VariableSpec",
    "VerificationDiagnostic",
    "VerificationProblem",
    "PolynomialRequirementReport",
    "CertificateTrajectoryDiagnostics",
    "certificate_series_for_trajectory",
    "classifications_by_obligation",
    "dynamics_spec_from_controlled",
    "dynamics_spec_from_controlled_discrete",
    "dynamics_spec_from_discrete",
    "dynamics_spec_from_system",
    "expression_spec",
    "inspection_diagnostics",
    "obligation_classifications",
    "render_inspection_markdown",
    "scalar_field_region_geometries",
    "scalar_field_region_geometry",
    "sampled_region_proof_statuses",
    "sos_polynomial_requirement_diagnostics",
    "verification_problem_from_barrier",
    "verification_problem_from_controlled_discrete_barrier",
    "verification_problem_from_controlled_discrete_lyapunov",
    "verification_problem_from_discrete_barrier",
    "verification_problem_from_discrete_lyapunov",
    "verification_problem_from_lyapunov",
    "verification_problem_from_obligations",
    "validate_inspection_artifact_index",
    "write_inspection_artifacts",
]
