/**
 * The shared example manifest, generated by the Python engine.
 *
 * These types mirror `engine/export/manifest.py`. The manifest is Python's
 * single source of truth: titles, tunable parameters, the named state schema,
 * projections (named groups of state variables that replace magic indices),
 * conserved quantities with their generating symmetry, the visualization
 * lenses, and the symbolic physics rendered as LaTeX.
 */

export type ParameterRole = "physical" | "initial";

export interface ManifestParameter {
  name: string;
  latex: string;
  default: number;
  min: number;
  max: number;
  role: ParameterRole;
}

export type StateKind = "coordinate" | "velocity" | "momentum" | "embedding";

export interface ManifestStateVar {
  name: string;
  latex: string;
  kind: StateKind;
}

export interface ManifestConserved {
  name: string;
  latex: string;
  symmetry: string;
  expression_latex?: string;
  generator_latex?: string[];
  tau_latex?: string;
}

export interface ManifestPhysics {
  lagrangian: string;
  hamiltonian: string | null;
  energy: string;
  euler_lagrange: string[];
}

export interface ManifestDerivationLagrangian {
  expression_latex: string;
}

export interface ManifestDerivationMomentum {
  coordinate: string;
  velocity: string;
  momentum: string;
  momentum_latex: string;
  expression_latex: string;
  equation_latex: string;
}

export interface ManifestDerivationEquation {
  coordinate?: string;
  equation_latex: string;
}

export interface ManifestDerivationLegendre {
  regular: boolean;
  velocity_solutions: Array<{
    velocity: string;
    expression_latex: string;
    equation_latex: string;
  }>;
}

export interface ManifestDerivationHamiltonian {
  expression_latex: string;
  equations: ManifestDerivationEquation[];
}

export interface ManifestDerivationConserved {
  name: string;
  symbol_latex: string;
  symmetry: string;
  charge_latex?: string;
  generator_latex?: string[];
  tau_latex?: string;
}

export interface ManifestEffectivePotential {
  name: string;
  coordinate: string;
  latex: string;
  conserved: string;
  conserved_latex: string;
  expression_latex: string;
}

export interface ManifestLens {
  id: string;
  title: string;
  kind: string;
  description: string;
  projections: string[];
  conserved: string[];
  effectivePotentials: string[];
}

export interface ManifestDerivation {
  lagrangian: ManifestDerivationLagrangian;
  generalized_momenta: ManifestDerivationMomentum[];
  euler_lagrange: ManifestDerivationEquation[];
  legendre_transform: ManifestDerivationLegendre;
  hamiltonian: ManifestDerivationHamiltonian | null;
  conserved_quantities: ManifestDerivationConserved[];
  effective_potentials: ManifestEffectivePotential[];
}

export interface ManifestDynamicsEquation {
  state: string;
  equation_latex: string;
  expression_latex: string;
}

export interface ManifestDynamics {
  vector_field: ManifestDynamicsEquation[];
  divergence_latex: string;
  jacobian_latex: string;
}

export interface SystemManifest {
  id: string;
  title: string;
  category: string;
  description: string;
  dataPath: string;
  systemKind?: "mechanics" | "first-order-flow" | string;
  parameters: ManifestParameter[];
  state: ManifestStateVar[];
  projections: Record<string, string[]>;
  conserved: ManifestConserved[];
  effectivePotentials: ManifestEffectivePotential[];
  lenses: string[];
  physics?: ManifestPhysics;
  derivation?: ManifestDerivation;
  dynamics?: ManifestDynamics;
}

export interface Manifest {
  version: number;
  lenses: ManifestLens[];
  systems: SystemManifest[];
}

const MANIFEST_PATH = "/data/manifest.json";

let pending: Promise<Manifest> | null = null;

/** Load (and cache) the manifest. A failed load is not cached, so it can retry. */
export function loadManifest(path = MANIFEST_PATH): Promise<Manifest> {
  if (!pending) {
    pending = fetch(path)
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Unable to load manifest: ${response.status}`);
        }
        return response.json() as Promise<Manifest>;
      })
      .catch((error) => {
        pending = null;
        throw error;
      });
  }
  return pending;
}

export function findSystem(manifest: Manifest, id: string): SystemManifest | undefined {
  return manifest.systems.find((system) => system.id === id);
}
