/**
 * The shared example manifest, generated by the Python engine.
 *
 * These types mirror `engine/export/manifest.py`. The manifest is Python's
 * single source of truth: titles, tunable parameters, the named state schema,
 * projections (named groups of state variables that replace magic indices),
 * conserved quantities with their generating symmetry, the visualization
 * lenses, and the symbolic physics rendered as LaTeX.
 */

export type ParameterRole = "physical" | "initial";

export interface ManifestParameter {
  name: string;
  latex: string;
  default: number;
  min: number;
  max: number;
  role: ParameterRole;
}

export type StateKind = "coordinate" | "velocity" | "momentum" | "embedding";

export interface ManifestStateVar {
  name: string;
  latex: string;
  kind: StateKind;
}

export interface ManifestConserved {
  name: string;
  latex: string;
  symmetry: string;
  expression_latex?: string;
}

export interface ManifestPhysics {
  lagrangian: string;
  hamiltonian: string | null;
  energy: string;
  euler_lagrange: string[];
}

export interface SystemManifest {
  id: string;
  title: string;
  category: string;
  description: string;
  dataPath: string;
  parameters: ManifestParameter[];
  state: ManifestStateVar[];
  projections: Record<string, string[]>;
  conserved: ManifestConserved[];
  lenses: string[];
  physics: ManifestPhysics;
}

export interface Manifest {
  version: number;
  systems: SystemManifest[];
}

const MANIFEST_PATH = "/data/manifest.json";

let pending: Promise<Manifest> | null = null;

/** Load (and cache) the manifest. A failed load is not cached, so it can retry. */
export function loadManifest(path = MANIFEST_PATH): Promise<Manifest> {
  if (!pending) {
    pending = fetch(path)
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Unable to load manifest: ${response.status}`);
        }
        return response.json() as Promise<Manifest>;
      })
      .catch((error) => {
        pending = null;
        throw error;
      });
  }
  return pending;
}

export function findSystem(manifest: Manifest, id: string): SystemManifest | undefined {
  return manifest.systems.find((system) => system.id === id);
}
