/**
 * The verification-problem IR, generated by the Python engine.
 *
 * These types mirror `engine/verification/ir.py`, serialized by
 * `scripts/generate_verification_problems.py`. The IR is the verification-layer
 * analogue of the manifest: it carries the model, regions, candidate
 * certificates, and proof obligations an external sound method would have to
 * discharge. The engine **proposes and organizes; external tools dispose** —
 * nothing in the IR records a proof result, and the viewer renders that honesty
 * verbatim (every obligation stays `external-required`; candidates stay
 * `candidate`).
 *
 * Parsing is intentionally defensive: the IR is under active backend
 * development, so unknown or added fields are ignored rather than fatal, and any
 * missing optional section degrades to empty instead of throwing.
 */

export interface IrExpression {
  /** Human-readable rendering, e.g. `omega**2/2 + ...`. */
  display: string;
  /** LaTeX rendering for KaTeX; falls back to `display` when absent. */
  latex: string;
}

export interface IrVariable {
  name: string;
  latex: string;
}

export interface IrParameter {
  name: string;
  latex: string;
}

export type RegionRole = "safe" | "unsafe" | "initial" | "domain" | string;

export interface IrRegion {
  id: string;
  name: string;
  kind: string;
  role: RegionRole;
  variables: string[];
  expression: IrExpression | null;
  level: number | null;
  convention: string | null;
}

export interface IrObligation {
  id: string;
  name: string;
  expression: IrExpression | null;
  comparison: string;
  rhs: number | null;
  description: string | null;
  /** The rigor ladder label; the engine never emits "proved"/"certified". */
  rigor: string;
  regionId: string | null;
  assumptionIds: string[];
}

export type CandidateKind = "lyapunov" | "barrier" | string;

export interface IrCandidate {
  id: string;
  name: string;
  kind: CandidateKind;
  status: string;
  expression: IrExpression | null;
  regionId: string | null;
  obligationIds: string[];
}

export interface IrAssumption {
  id: string;
  description: string | null;
  expression: IrExpression | null;
}

export interface IrDynamics {
  kind: string;
  state: string[];
  inputs: IrInput[];
  timeVariable: string | null;
  rhs: IrExpression[];
}

export interface IrInput {
  name: string;
  role: string | null;
  lower: number | null;
  upper: number | null;
}

export interface VerificationProblem {
  schemaVersion: string;
  id: string;
  name: string;
  source: string | null;
  variables: IrVariable[];
  parameters: IrParameter[];
  regions: IrRegion[];
  assumptions: IrAssumption[];
  obligations: IrObligation[];
  candidates: IrCandidate[];
  dynamics: IrDynamics | null;
  metadata: Record<string, unknown>;
}

export interface VerificationProblemSummary {
  id: string;
  name: string;
  system: string | null;
  status: string;
  schemaVersion: string | null;
  dataPath: string;
  counts: { regions: number; obligations: number; candidates: number };
}

export interface VerificationIndex {
  version: number;
  problems: VerificationProblemSummary[];
}

const INDEX_PATH = "/data/verification/index.json";

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : undefined;
}

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function asOptionalString(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}

function asOptionalNumber(value: unknown): number | null {
  return typeof value === "number" ? value : null;
}

function asStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

// An IR expression carries `display` and `latex`; we prefer `latex` for KaTeX
// but never fail if only one is present.
function parseExpression(value: unknown): IrExpression | null {
  const record = asRecord(value);
  if (!record) {
    return null;
  }
  const display = asString(record.display);
  const latex = asString(record.latex, display);
  if (!display && !latex) {
    return null;
  }
  return { display, latex: latex || display };
}

function parseVariable(value: unknown): IrVariable | null {
  const record = asRecord(value);
  if (!record || typeof record.name !== "string") {
    return null;
  }
  return { name: record.name, latex: asString(record.latex, record.name) };
}

function parseRegion(value: unknown): IrRegion | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    name: asString(record.name, record.id),
    kind: asString(record.kind),
    role: asString(record.role, "domain"),
    variables: asStringArray(record.variables),
    expression: parseExpression(record.expression),
    level: asOptionalNumber(record.level),
    convention: asOptionalString(record.convention),
  };
}

function parseObligation(value: unknown): IrObligation | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    name: asString(record.name, record.id),
    expression: parseExpression(record.expression),
    comparison: asString(record.comparison),
    rhs: asOptionalNumber(record.rhs),
    description: asOptionalString(record.description),
    rigor: asString(record.rigor, "external-required"),
    regionId: asOptionalString(record.regionId),
    assumptionIds: asStringArray(record.assumptionIds),
  };
}

function parseCandidate(value: unknown): IrCandidate | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    name: asString(record.name, record.id),
    kind: asString(record.kind, "candidate"),
    status: asString(record.status, "candidate"),
    expression: parseExpression(record.expression),
    regionId: asOptionalString(record.regionId),
    obligationIds: asStringArray(record.obligationIds),
  };
}

function parseAssumption(value: unknown): IrAssumption | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    description: asOptionalString(record.description),
    expression: parseExpression(record.expression),
  };
}

function parseInput(value: unknown): IrInput | null {
  const record = asRecord(value);
  if (!record || typeof record.name !== "string") {
    return null;
  }
  return {
    name: record.name,
    role: asOptionalString(record.role),
    lower: asOptionalNumber(record.lower),
    upper: asOptionalNumber(record.upper),
  };
}

function parseDynamics(value: unknown): IrDynamics | null {
  const record = asRecord(value);
  if (!record) {
    return null;
  }
  const rhs = Array.isArray(record.rhs)
    ? record.rhs.flatMap((item) => {
        const expression = parseExpression(item);
        return expression ? [expression] : [];
      })
    : [];
  const inputs = Array.isArray(record.inputs)
    ? record.inputs.flatMap((item) => {
        const input = parseInput(item);
        return input ? [input] : [];
      })
    : [];
  return {
    kind: asString(record.kind, "continuous"),
    state: asStringArray(record.state),
    inputs,
    timeVariable: asOptionalString(record.timeVariable),
    rhs,
  };
}

function parseArray<T>(value: unknown, parse: (item: unknown) => T | null): T[] {
  return Array.isArray(value) ? value.flatMap((item) => {
    const parsed = parse(item);
    return parsed ? [parsed] : [];
  }) : [];
}

export function parseVerificationProblem(raw: unknown): VerificationProblem {
  const record = asRecord(raw) ?? {};
  return {
    schemaVersion: asString(record.schemaVersion, "unknown"),
    id: asString(record.id, "problem"),
    name: asString(record.name, asString(record.id, "Verification problem")),
    source: asOptionalString(record.source),
    variables: parseArray(record.variables, parseVariable),
    parameters: parseArray(record.parameters, parseVariable),
    regions: parseArray(record.regions, parseRegion),
    assumptions: parseArray(record.assumptions, parseAssumption),
    obligations: parseArray(record.obligations, parseObligation),
    candidates: parseArray(record.candidates, parseCandidate),
    dynamics: parseDynamics(record.dynamics),
    metadata: asRecord(record.metadata) ?? {},
  };
}

function parseSummary(value: unknown): VerificationProblemSummary | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string" || typeof record.dataPath !== "string") {
    return null;
  }
  const counts = asRecord(record.counts) ?? {};
  return {
    id: record.id,
    name: asString(record.name, record.id),
    system: asOptionalString(record.system),
    status: asString(record.status, "candidate"),
    schemaVersion: asOptionalString(record.schemaVersion),
    dataPath: record.dataPath,
    counts: {
      regions: asOptionalNumber(counts.regions) ?? 0,
      obligations: asOptionalNumber(counts.obligations) ?? 0,
      candidates: asOptionalNumber(counts.candidates) ?? 0,
    },
  };
}

/**
 * Load the verification index. A missing index (data not yet generated) is not
 * an error — it resolves to an empty list so the Verification domain can show a
 * help message instead of crashing.
 */
export async function loadVerificationIndex(path = INDEX_PATH): Promise<VerificationIndex> {
  try {
    const response = await fetch(path);
    if (!response.ok) {
      return { version: 0, problems: [] };
    }
    const raw = (await response.json()) as unknown;
    const record = asRecord(raw) ?? {};
    return {
      version: asOptionalNumber(record.version) ?? 0,
      problems: parseArray(record.problems, parseSummary),
    };
  } catch (error) {
    console.warn("Verification index unavailable:", error);
    return { version: 0, problems: [] };
  }
}

/** Load and parse a single verification problem's IR. */
export async function loadVerificationProblem(dataPath: string): Promise<VerificationProblem> {
  const response = await fetch(dataPath);
  if (!response.ok) {
    throw new Error(`Unable to load verification problem: ${response.status}`);
  }
  return parseVerificationProblem((await response.json()) as unknown);
}
