/**
 * The verification-problem IR, generated by the Python engine.
 *
 * These types mirror `engine/verification/ir.py`, serialized by
 * `scripts/generate_verification_problems.py`. The IR is the verification-layer
 * analogue of the manifest: it carries the model, regions, candidate
 * certificates, and proof obligations an external sound method would have to
 * discharge. The engine **proposes and organizes; external tools dispose** —
 * nothing in the IR records a proof result, and the viewer renders that honesty
 * verbatim (every obligation stays `external-required`; candidates stay
 * `candidate`).
 *
 * Parsing is intentionally defensive: the IR is under active backend
 * development, so unknown or added fields are ignored rather than fatal, and any
 * missing optional section degrades to empty instead of throwing.
 */

import { parseCertificateSeriesList, type CertificateSeries } from "./trajectory";

export interface IrExpression {
  /** Human-readable rendering, e.g. `omega**2/2 + ...`. */
  display: string;
  /** LaTeX rendering for KaTeX; falls back to `display` when absent. */
  latex: string;
}

/**
 * The self-contained trajectory the Verification world animates: the controlled
 * system the obligations are derived for, integrated by the engine, with
 * candidate-certificate series evaluated along it. Exported in the problem JSON
 * under `trajectory` (its own state, independent of any gallery system).
 */
export interface VerificationTrajectory {
  time: number[];
  stateNames: string[];
  states: number[][];
  series: Record<string, number[]>;
  certificateSeries: CertificateSeries[];
}

export interface IrVariable {
  name: string;
  latex: string;
}

export interface IrParameter {
  name: string;
  latex: string;
}

export type RegionRole = "safe" | "unsafe" | "initial" | "domain" | string;

export interface IrRegion {
  id: string;
  name: string;
  kind: string;
  role: RegionRole;
  variables: string[];
  expression: IrExpression | null;
  level: number | null;
  convention: string | null;
}

/**
 * Measured visualization geometry for one region: the region's defining
 * function sampled over a deterministic 2-D grid on a named projection. The
 * symbolic region in `IrRegion` remains the verification claim; this exists only
 * so the viewer can shade the set without re-evaluating symbolic inequalities.
 * `convention` (e.g. "expression <= level") says which side of `level` is inside.
 */
export interface RegionGeometryPlane {
  /** The region's own variable names, e.g. ["theta", "omega"]. */
  variables: string[];
  /** The trajectory state axes those variables map onto, e.g. ["theta", "theta_dot"]. */
  stateAxes: string[];
  variableToStateAxis: Record<string, string>;
}

export interface RegionGeometryGrid {
  /** Sample coordinates along the first plane variable. */
  x: number[];
  /** Sample coordinates along the second plane variable. */
  y: number[];
  /** Field values indexed [yIndex][xIndex]. */
  values: number[][];
}

export interface RegionGeometry {
  regionId: string;
  role: RegionRole;
  kind: string;
  projection: string;
  plane: RegionGeometryPlane;
  grid: RegionGeometryGrid;
  /** Backend-traced level-set outlines, each a polyline of `[x, y]` plane points. */
  boundaryPolylines: Array<Array<[number, number]>>;
  level: number | null;
  convention: string | null;
}

export interface IrObligation {
  id: string;
  name: string;
  expression: IrExpression | null;
  comparison: string;
  rhs: number | null;
  description: string | null;
  /** The rigor ladder label; the engine never emits "proved"/"certified". */
  rigor: string;
  regionId: string | null;
  assumptionIds: string[];
}

export type CandidateKind = "lyapunov" | "barrier" | string;

export interface IrCandidate {
  id: string;
  name: string;
  kind: CandidateKind;
  status: string;
  expression: IrExpression | null;
  regionId: string | null;
  obligationIds: string[];
}

/**
 * A measured status record for one obligation evaluation surface, exported in
 * `proofStatuses`. The backend sampled the obligation inequality somewhere (a
 * region grid, a trajectory) and recorded whether the samples satisfied it.
 * This is sampled evidence only: `externalStatus` stays `external-required`
 * regardless of `status`, and the engine never claims a proof or certificate.
 */
export type ProofStatusKind = "measured-holds" | "measured-violated" | "external-required" | string;

/**
 * How a sampled proof-status point projects onto trajectory state axes. The
 * worst point is reported in `variables` order; `variableToStateAxis` says which
 * trajectory state axis each plane variable corresponds to, so the viewer can
 * place the sample on the stage without re-deriving the projection.
 */
export interface ProofStatusProjection {
  variables: string[];
  stateAxes: string[];
  variableToStateAxis: Record<string, string>;
}

export interface ProofStatus {
  id: string;
  obligationId: string;
  status: ProofStatusKind;
  rigor: string;
  externalStatus: string;
  comparison: string;
  rhs: number;
  candidateId: string | null;
  regionId: string | null;
  evaluationKind: string;
  sampleCount: number;
  source: string | null;
  worstValue: number | null;
  /**
   * The signed worst margin to the obligation boundary (BE-036): nonnegative
   * when the sampled check held, negative when a sample violated it. Null when
   * the backend exported no worst record.
   */
  worstMargin: number | null;
  /** The worst sampled point, in `projection.variables` order; null if absent. */
  worstPoint: number[] | null;
  /** The sampled point's projection onto state axes; null when not exported. */
  projection: ProofStatusProjection | null;
  note: string | null;
}

export interface IrAssumption {
  id: string;
  description: string | null;
  expression: IrExpression | null;
  /** The bound comparison and right-hand side, when the assumption is an
   * inequality (e.g. a disturbance/wind box `|w| <= w_max`). */
  comparison: string;
  rhs: number | null;
}

export interface IrDynamics {
  kind: string;
  state: string[];
  inputs: IrInput[];
  timeVariable: string | null;
  rhs: IrExpression[];
}

export interface IrInput {
  name: string;
  role: string | null;
  lower: number | null;
  upper: number | null;
}

export interface VerificationProblem {
  schemaVersion: string;
  id: string;
  name: string;
  source: string | null;
  /** The manifest system id this problem is derived along, when linked. */
  system: string | null;
  variables: IrVariable[];
  parameters: IrParameter[];
  regions: IrRegion[];
  regionGeometry: RegionGeometry[];
  assumptions: IrAssumption[];
  obligations: IrObligation[];
  candidates: IrCandidate[];
  proofStatuses: ProofStatus[];
  dynamics: IrDynamics | null;
  trajectory: VerificationTrajectory | null;
  metadata: Record<string, unknown>;
}

export interface VerificationProblemSummary {
  id: string;
  name: string;
  /** The self-contained model the problem describes (no gallery cross-link). */
  model: string | null;
  status: string;
  schemaVersion: string | null;
  dataPath: string;
  /** The backend-agnostic IR artifact path, when the export published one. */
  irPath: string | null;
  /**
   * The self-contained BE-039 package manifest path, when the export published
   * one: a `package.json` indexing the IR, viewer trajectory, and any inspection
   * report so the problem can be presented and exported as a single bundle.
   */
  packagePath: string | null;
  counts: { regions: number; obligations: number; candidates: number };
}

export interface VerificationIndex {
  version: number;
  problems: VerificationProblemSummary[];
}

/**
 * The Tier/regime descriptor a package carries in the discovery index (BE-054):
 * `nominal` for Tier-1/2 packages, `disturbance-robust` for Tier-3 ones (quantified
 * over a wind box). It claims nothing beyond the rigor of the listed package.
 */
export interface PackageRegime {
  kind: string;
  disturbanceParameters: string[];
  robustObligationIds: string[];
}

const INDEX_PATH = "/data/verification/index.json";
const PACKAGE_INDEX_PATH = "/data/verification/packages/packages.index.json";

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : undefined;
}

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function asOptionalString(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}

function asOptionalNumber(value: unknown): number | null {
  return typeof value === "number" ? value : null;
}

function asStringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

function asNumberArray(value: unknown): number[] {
  return Array.isArray(value) ? value.filter((item): item is number => typeof item === "number") : [];
}

function asStringRecord(value: unknown): Record<string, string> {
  const record = asRecord(value);
  if (!record) {
    return {};
  }
  const result: Record<string, string> = {};
  for (const [key, raw] of Object.entries(record)) {
    if (typeof raw === "string") {
      result[key] = raw;
    }
  }
  return result;
}

// An IR expression carries `display` and `latex`; we prefer `latex` for KaTeX
// but never fail if only one is present.
function parseExpression(value: unknown): IrExpression | null {
  const record = asRecord(value);
  if (!record) {
    return null;
  }
  const display = asString(record.display);
  const latex = asString(record.latex, display);
  if (!display && !latex) {
    return null;
  }
  return { display, latex: latex || display };
}

function parseVariable(value: unknown): IrVariable | null {
  const record = asRecord(value);
  if (!record || typeof record.name !== "string") {
    return null;
  }
  return { name: record.name, latex: asString(record.latex, record.name) };
}

function parseRegion(value: unknown): IrRegion | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    name: asString(record.name, record.id),
    kind: asString(record.kind),
    role: asString(record.role, "domain"),
    variables: asStringArray(record.variables),
    expression: parseExpression(record.expression),
    level: asOptionalNumber(record.level),
    convention: asOptionalString(record.convention),
  };
}

function parsePolylines(value: unknown): Array<Array<[number, number]>> {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.flatMap((line) => {
    if (!Array.isArray(line)) {
      return [];
    }
    const points = line.flatMap((point): [number, number][] =>
      Array.isArray(point) && typeof point[0] === "number" && typeof point[1] === "number"
        ? [[point[0], point[1]]]
        : [],
    );
    return points.length >= 2 ? [points] : [];
  });
}

function parseRegionGeometry(value: unknown): RegionGeometry | null {
  const record = asRecord(value);
  if (!record || typeof record.regionId !== "string") {
    return null;
  }
  const plane = asRecord(record.plane) ?? {};
  const grid = asRecord(record.grid) ?? {};
  const values = Array.isArray(grid.values) ? grid.values.map(asNumberArray) : [];
  return {
    regionId: record.regionId,
    role: asString(record.role, "domain"),
    kind: asString(record.kind),
    projection: asString(record.projection),
    plane: {
      variables: asStringArray(plane.variables),
      stateAxes: asStringArray(plane.stateAxes),
      variableToStateAxis: asStringRecord(plane.variableToStateAxis),
    },
    grid: {
      x: asNumberArray(grid.x),
      y: asNumberArray(grid.y),
      values,
    },
    boundaryPolylines: parsePolylines(record.boundaryPolylines),
    level: asOptionalNumber(record.level),
    convention: asOptionalString(record.convention),
  };
}

function parseObligation(value: unknown): IrObligation | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    name: asString(record.name, record.id),
    expression: parseExpression(record.expression),
    comparison: asString(record.comparison),
    rhs: asOptionalNumber(record.rhs),
    description: asOptionalString(record.description),
    rigor: asString(record.rigor, "external-required"),
    regionId: asOptionalString(record.regionId),
    assumptionIds: asStringArray(record.assumptionIds),
  };
}

function parseCandidate(value: unknown): IrCandidate | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    name: asString(record.name, record.id),
    kind: asString(record.kind, "candidate"),
    status: asString(record.status, "candidate"),
    expression: parseExpression(record.expression),
    regionId: asOptionalString(record.regionId),
    obligationIds: asStringArray(record.obligationIds),
  };
}

function parseProofStatus(value: unknown): ProofStatus | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string" || typeof record.obligationId !== "string") {
    return null;
  }
  const evaluation = asRecord(record.evaluation) ?? {};
  const worst = asRecord(record.worst);
  const worstPoint = worst ? asNumberArray(worst.point) : [];
  const projectionVariables = asStringArray(evaluation.variables);
  return {
    id: record.id,
    obligationId: record.obligationId,
    status: asString(record.status, "external-required"),
    rigor: asString(record.rigor, "measured"),
    externalStatus: asString(record.externalStatus, "external-required"),
    comparison: asString(record.comparison),
    rhs: asOptionalNumber(record.rhs) ?? 0,
    candidateId: asOptionalString(record.candidateId),
    regionId: asOptionalString(record.regionId),
    evaluationKind: asString(evaluation.kind),
    sampleCount: asOptionalNumber(evaluation.sampleCount) ?? 0,
    source: asOptionalString(evaluation.source),
    worstValue: worst ? asOptionalNumber(worst.value) : null,
    worstMargin: worst ? asOptionalNumber(worst.margin) : null,
    worstPoint: worstPoint.length > 0 ? worstPoint : null,
    projection:
      projectionVariables.length > 0
        ? {
            variables: projectionVariables,
            stateAxes: asStringArray(evaluation.stateAxes),
            variableToStateAxis: asStringRecord(evaluation.variableToStateAxis),
          }
        : null,
    note: asOptionalString(record.note),
  };
}

function parseAssumption(value: unknown): IrAssumption | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string") {
    return null;
  }
  return {
    id: record.id,
    description: asOptionalString(record.description),
    expression: parseExpression(record.expression),
    comparison: asString(record.comparison, "<="),
    rhs: asOptionalNumber(record.rhs),
  };
}

function parseInput(value: unknown): IrInput | null {
  const record = asRecord(value);
  if (!record || typeof record.name !== "string") {
    return null;
  }
  return {
    name: record.name,
    role: asOptionalString(record.role),
    lower: asOptionalNumber(record.lower),
    upper: asOptionalNumber(record.upper),
  };
}

function parseVerificationTrajectory(value: unknown): VerificationTrajectory | null {
  const record = asRecord(value);
  if (!record) {
    return null;
  }
  const time = asNumberArray(record.time);
  const states = Array.isArray(record.states) ? record.states.map(asNumberArray) : [];
  if (time.length === 0 || states.length === 0) {
    return null;
  }
  const seriesRecord = asRecord(record.series) ?? {};
  const series: Record<string, number[]> = {};
  for (const [key, raw] of Object.entries(seriesRecord)) {
    series[key] = asNumberArray(raw);
  }
  return {
    time,
    stateNames: asStringArray(record.stateNames),
    states,
    series,
    certificateSeries: parseCertificateSeriesList(record.certificateSeries),
  };
}

function parseDynamics(value: unknown): IrDynamics | null {
  const record = asRecord(value);
  if (!record) {
    return null;
  }
  const rhs = Array.isArray(record.rhs)
    ? record.rhs.flatMap((item) => {
        const expression = parseExpression(item);
        return expression ? [expression] : [];
      })
    : [];
  const inputs = Array.isArray(record.inputs)
    ? record.inputs.flatMap((item) => {
        const input = parseInput(item);
        return input ? [input] : [];
      })
    : [];
  return {
    kind: asString(record.kind, "continuous"),
    state: asStringArray(record.state),
    inputs,
    timeVariable: asOptionalString(record.timeVariable),
    rhs,
  };
}

function parseArray<T>(value: unknown, parse: (item: unknown) => T | null): T[] {
  return Array.isArray(value) ? value.flatMap((item) => {
    const parsed = parse(item);
    return parsed ? [parsed] : [];
  }) : [];
}

export function parseVerificationProblem(raw: unknown): VerificationProblem {
  const record = asRecord(raw) ?? {};
  return {
    schemaVersion: asString(record.schemaVersion, "unknown"),
    id: asString(record.id, "problem"),
    name: asString(record.name, asString(record.id, "Verification problem")),
    source: asOptionalString(record.source),
    system: asOptionalString(record.system),
    variables: parseArray(record.variables, parseVariable),
    parameters: parseArray(record.parameters, parseVariable),
    regions: parseArray(record.regions, parseRegion),
    regionGeometry: parseArray(record.regionGeometry, parseRegionGeometry),
    assumptions: parseArray(record.assumptions, parseAssumption),
    obligations: parseArray(record.obligations, parseObligation),
    candidates: parseArray(record.candidates, parseCandidate),
    proofStatuses: parseArray(record.proofStatuses, parseProofStatus),
    dynamics: parseDynamics(record.dynamics),
    trajectory: parseVerificationTrajectory(record.trajectory),
    metadata: asRecord(record.metadata) ?? {},
  };
}

function parseSummary(value: unknown): VerificationProblemSummary | null {
  const record = asRecord(value);
  if (!record || typeof record.id !== "string" || typeof record.dataPath !== "string") {
    return null;
  }
  const counts = asRecord(record.counts) ?? {};
  return {
    id: record.id,
    name: asString(record.name, record.id),
    model: asOptionalString(record.model),
    status: asString(record.status, "candidate"),
    schemaVersion: asOptionalString(record.schemaVersion),
    dataPath: record.dataPath,
    irPath: asOptionalString(record.irPath),
    packagePath: asOptionalString(record.packagePath),
    counts: {
      regions: asOptionalNumber(counts.regions) ?? 0,
      obligations: asOptionalNumber(counts.obligations) ?? 0,
      candidates: asOptionalNumber(counts.candidates) ?? 0,
    },
  };
}

/**
 * Load the verification index. A missing index (data not yet generated) is not
 * an error — it resolves to an empty list so the Verification domain can show a
 * help message instead of crashing.
 */
export async function loadVerificationIndex(path = INDEX_PATH): Promise<VerificationIndex> {
  try {
    const response = await fetch(path);
    if (!response.ok) {
      return { version: 0, problems: [] };
    }
    const raw = (await response.json()) as unknown;
    const record = asRecord(raw) ?? {};
    return {
      version: asOptionalNumber(record.version) ?? 0,
      problems: parseArray(record.problems, parseSummary),
    };
  } catch (error) {
    console.warn("Verification index unavailable:", error);
    return { version: 0, problems: [] };
  }
}

function parseRegime(value: unknown): PackageRegime | null {
  const record = asRecord(value);
  if (!record || typeof record.kind !== "string") {
    return null;
  }
  return {
    kind: record.kind,
    disturbanceParameters: asStringArray(record.disturbanceParameters),
    robustObligationIds: asStringArray(record.robustObligationIds),
  };
}

/**
 * Load the package discovery index's Tier/regime descriptors (BE-054), keyed by
 * problem id, so the catalog can badge each entry by its regime without opening
 * it. A missing or malformed index resolves to an empty map, so entries simply
 * carry no badge.
 */
export async function loadVerificationPackageRegimes(
  path = PACKAGE_INDEX_PATH,
): Promise<Map<string, PackageRegime>> {
  const regimes = new Map<string, PackageRegime>();
  try {
    const response = await fetch(path);
    if (!response.ok) {
      return regimes;
    }
    const record = asRecord((await response.json()) as unknown) ?? {};
    for (const entry of parseArray(record.packages, (item) => asRecord(item) ?? null)) {
      if (typeof entry.problemId !== "string") {
        continue;
      }
      const regime = parseRegime(entry.regime);
      if (regime) {
        regimes.set(entry.problemId, regime);
      }
    }
  } catch (error) {
    console.warn("Verification package index unavailable:", error);
  }
  return regimes;
}

/** Load and parse a single verification problem's IR. */
export async function loadVerificationProblem(dataPath: string): Promise<VerificationProblem> {
  const response = await fetch(dataPath);
  if (!response.ok) {
    throw new Error(`Unable to load verification problem: ${response.status}`);
  }
  return parseVerificationProblem((await response.json()) as unknown);
}

/**
 * The BE-039 verification package, mirroring `engine/export/verification_package.py`.
 * A `package.json` manifest indexes the bundle's component files (the IR, the
 * viewer trajectory, and any inspection report). Like the rest of the verification
 * layer it claims nothing: `status` stays `candidate`, and the components carry
 * the same honest rigor as the standalone problem.
 */
export interface PackageComponent {
  /** e.g. `problem-ir`, `viewer-trajectory`, `inspection-report`. */
  kind: string;
  /** The component filename, relative to the package directory. */
  path: string;
  description: string;
}

export interface PackageManifest {
  schemaVersion: string;
  problemId: string;
  name: string;
  model: string;
  status: string;
  counts: { regions: number; obligations: number; candidates: number };
  components: PackageComponent[];
}

/**
 * The non-discharging adapter-stub descriptors (BE-044), an optional package
 * component. Each stub names an external backend category that *could* consume
 * an obligation and the obligation shape it would have to handle. Every stub is
 * a tool-agnostic pointer only: `discharges` is always false, and every
 * obligation stays external-required.
 */
export interface AdapterCategory {
  category: string;
  summary: string;
  consumesTargets: string[];
  consumes: string;
  produces: string;
}

export interface AdapterStub {
  obligationId: string;
  category: string;
  target: string;
  applicable: boolean;
  requiredShapeFeatures: string[];
  /** Always false: a stub is a descriptor, never a discharge. */
  discharges: boolean;
  note: string | null;
}

export interface AdapterStubs {
  problemId: string;
  note: string | null;
  categories: AdapterCategory[];
  stubs: AdapterStub[];
}

/** A single self-contained bundle assembled for download: the manifest plus each
 * component's payload, keyed by component kind. Re-reading it recovers the same
 * components the backend wrote. */
export interface VerificationPackageBundle {
  schemaVersion: string;
  manifest: Record<string, unknown>;
  components: Record<string, unknown>;
}

function parsePackageComponent(value: unknown): PackageComponent | null {
  const record = asRecord(value);
  if (!record || typeof record.kind !== "string" || typeof record.path !== "string") {
    return null;
  }
  return {
    kind: record.kind,
    path: record.path,
    description: asString(record.description),
  };
}

function parsePackageManifest(raw: unknown): PackageManifest | null {
  const record = asRecord(raw);
  if (!record || typeof record.problemId !== "string") {
    return null;
  }
  const components = parseArray(record.components, parsePackageComponent);
  if (components.length === 0) {
    return null;
  }
  const counts = asRecord(record.counts) ?? {};
  return {
    schemaVersion: asString(record.schemaVersion, "unknown"),
    problemId: record.problemId,
    name: asString(record.name, record.problemId),
    model: asString(record.model),
    status: asString(record.status, "candidate"),
    counts: {
      regions: asOptionalNumber(counts.regions) ?? 0,
      obligations: asOptionalNumber(counts.obligations) ?? 0,
      candidates: asOptionalNumber(counts.candidates) ?? 0,
    },
    components,
  };
}

// The directory a package manifest lives in, so component paths (relative
// filenames) can be resolved against it.
function packageBasePath(packagePath: string): string {
  return packagePath.slice(0, packagePath.lastIndexOf("/"));
}

/**
 * Load a problem's package manifest. A missing or malformed manifest (data not
 * yet generated, older export) resolves to null rather than throwing, so the
 * Verification view can simply omit the package affordance.
 */
export async function loadVerificationPackageManifest(
  packagePath: string,
): Promise<PackageManifest | null> {
  try {
    const response = await fetch(packagePath);
    if (!response.ok) {
      return null;
    }
    return parsePackageManifest((await response.json()) as unknown);
  } catch (error) {
    console.warn("Verification package manifest unavailable:", error);
    return null;
  }
}

function parseAdapterCategory(value: unknown): AdapterCategory | null {
  const record = asRecord(value);
  if (!record || typeof record.category !== "string") {
    return null;
  }
  return {
    category: record.category,
    summary: asString(record.summary),
    consumesTargets: asStringArray(record.consumesTargets),
    consumes: asString(record.consumes),
    produces: asString(record.produces),
  };
}

function parseAdapterStub(value: unknown): AdapterStub | null {
  const record = asRecord(value);
  if (!record || typeof record.obligationId !== "string" || typeof record.category !== "string") {
    return null;
  }
  return {
    obligationId: record.obligationId,
    category: record.category,
    target: asString(record.target),
    applicable: record.applicable !== false,
    requiredShapeFeatures: asStringArray(record.requiredShapeFeatures),
    // A stub is a descriptor only: honor the exported value but never treat a
    // stub as discharging anything.
    discharges: record.discharges === true,
    note: asOptionalString(record.note),
  };
}

function parseAdapterStubs(raw: unknown): AdapterStubs | null {
  const record = asRecord(raw);
  if (!record || typeof record.problemId !== "string") {
    return null;
  }
  const stubs = parseArray(record.stubs, parseAdapterStub);
  if (stubs.length === 0) {
    return null;
  }
  return {
    problemId: record.problemId,
    note: asOptionalString(record.note),
    categories: parseArray(record.categories, parseAdapterCategory),
    stubs,
  };
}

/**
 * Load a package's non-discharging adapter-stub descriptors, when the manifest
 * indexes them. A package without the `adapter-stubs` component, or a missing /
 * malformed file, resolves to null so the view simply omits the section.
 */
export async function loadVerificationAdapterStubs(
  packagePath: string,
  manifest: PackageManifest,
): Promise<AdapterStubs | null> {
  const component = manifest.components.find((entry) => entry.kind === "adapter-stubs");
  if (!component) {
    return null;
  }
  try {
    const response = await fetch(`${packageBasePath(packagePath)}/${component.path}`);
    if (!response.ok) {
      return null;
    }
    return parseAdapterStubs((await response.json()) as unknown);
  } catch (error) {
    console.warn("Verification adapter stubs unavailable:", error);
    return null;
  }
}

/**
 * Assemble a problem's package into one self-contained bundle for download:
 * fetch the manifest and every component it indexes, embedding each component's
 * payload keyed by its kind. The embedded manifest is the backend's own, so the
 * bundle re-reads to exactly the components the backend wrote. Throws if any
 * indexed file is missing, so a download never silently drops a component.
 */
export async function assembleVerificationPackageBundle(
  packagePath: string,
): Promise<VerificationPackageBundle> {
  const manifestResponse = await fetch(packagePath);
  if (!manifestResponse.ok) {
    throw new Error(`Unable to load verification package: ${manifestResponse.status}`);
  }
  const manifestRaw = (await manifestResponse.json()) as Record<string, unknown>;
  const manifest = parsePackageManifest(manifestRaw);
  if (!manifest) {
    throw new Error("Verification package manifest is malformed.");
  }
  const base = packageBasePath(packagePath);
  const components: Record<string, unknown> = {};
  for (const component of manifest.components) {
    const response = await fetch(`${base}/${component.path}`);
    if (!response.ok) {
      throw new Error(`Missing package component ${component.kind} (${component.path}).`);
    }
    components[component.kind] = (await response.json()) as unknown;
  }
  return {
    schemaVersion: manifest.schemaVersion,
    manifest: manifestRaw,
    components,
  };
}
