from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import sympy as sp

from engine.dynamics import FirstOrderSystem, MetricGeometry
from engine.mechanics.coordinates import velocity_symbol

SurfaceFamily = Literal["sphere", "torus", "paraboloid", "cone", "hyperboloid"]


def _parameters_for(expressions: tuple[sp.Expr, ...], coordinate: sp.Symbol) -> tuple[sp.Symbol, ...]:
    symbols: set[sp.Symbol] = set()
    for expression in expressions:
        symbols.update(sp.sympify(expression).free_symbols)
    return tuple(sorted(symbols - {coordinate}, key=lambda symbol: symbol.name))


@dataclass(frozen=True)
class SurfaceOfRevolution:
    """A surface generated by revolving ``(rho(u), z(u))`` around the z-axis."""

    family: str
    meridian: sp.Symbol
    azimuth: sp.Symbol
    profile_radius: sp.Expr
    profile_height: sp.Expr
    parameters: tuple[sp.Symbol, ...] = ()

    def __post_init__(self) -> None:
        rho = sp.sympify(self.profile_radius)
        height = sp.sympify(self.profile_height)
        if self.meridian == self.azimuth:
            raise ValueError("meridian and azimuth coordinates must be distinct")
        if self.meridian not in rho.free_symbols | height.free_symbols:
            raise ValueError("surface profile must depend on the meridian coordinate")
        parameters = self.parameters or _parameters_for((rho, height), self.meridian)
        object.__setattr__(self, "profile_radius", rho)
        object.__setattr__(self, "profile_height", height)
        object.__setattr__(self, "parameters", tuple(parameters))

    @property
    def coordinates(self) -> tuple[sp.Symbol, sp.Symbol]:
        return (self.meridian, self.azimuth)

    @property
    def velocities(self) -> tuple[sp.Symbol, sp.Symbol]:
        return tuple(velocity_symbol(coordinate) for coordinate in self.coordinates)

    def first_fundamental_form(self) -> sp.Matrix:
        """Return the diagonal metric induced by the surface embedding."""

        u = self.meridian
        rho_u = sp.diff(self.profile_radius, u)
        z_u = sp.diff(self.profile_height, u)
        return sp.diag(
            sp.simplify(rho_u**2 + z_u**2),
            sp.simplify(self.profile_radius**2),
        )

    def metric_geometry(self) -> MetricGeometry:
        return MetricGeometry(
            coordinates=self.coordinates,
            metric=self.first_fundamental_form(),
            parameters=self.parameters,
        )

    def geodesic_system(self) -> FirstOrderSystem:
        return self.metric_geometry().geodesic_system()

    def embedding_expressions(self) -> tuple[sp.Expr, sp.Expr, sp.Expr]:
        u, phi = self.coordinates
        del u
        return (
            sp.simplify(self.profile_radius * sp.cos(phi)),
            sp.simplify(self.profile_radius * sp.sin(phi)),
            self.profile_height,
        )

    def embedding_tangent_expressions(self) -> tuple[tuple[sp.Expr, sp.Expr, sp.Expr], ...]:
        embedding = self.embedding_expressions()
        return tuple(
            tuple(sp.simplify(sp.diff(component, coordinate)) for component in embedding)
            for coordinate in self.coordinates
        )

    def clairaut_quantity(self) -> sp.Expr:
        """Cyclic azimuthal momentum ``rho(u)^2 phi_dot``."""

        _u_dot, phi_dot = self.velocities
        return sp.simplify(self.profile_radius**2 * phi_dot)

    def kinetic_energy(self) -> sp.Expr:
        return self.metric_geometry().kinetic_energy()

    def gaussian_curvature(self) -> sp.Expr:
        """Gaussian curvature from the two-dimensional scalar curvature."""

        return sp.simplify(self.metric_geometry().scalar_curvature() / 2)


def sphere_surface(radius: sp.Expr | float | None = None) -> SurfaceOfRevolution:
    theta = sp.Symbol("u", real=True)
    phi = sp.Symbol("phi", real=True)
    radius_value = sp.Symbol("R", positive=True) if radius is None else radius
    return SurfaceOfRevolution(
        family="sphere",
        meridian=theta,
        azimuth=phi,
        profile_radius=sp.sympify(radius_value) * sp.sin(theta),
        profile_height=sp.sympify(radius_value) * sp.cos(theta),
    )


def torus_surface(
    major_radius: sp.Expr | float | None = None,
    minor_radius: sp.Expr | float | None = None,
) -> SurfaceOfRevolution:
    u = sp.Symbol("u", real=True)
    phi = sp.Symbol("phi", real=True)
    major = sp.Symbol("R_major", positive=True) if major_radius is None else major_radius
    minor = sp.Symbol("r_minor", positive=True) if minor_radius is None else minor_radius
    return SurfaceOfRevolution(
        family="torus",
        meridian=u,
        azimuth=phi,
        profile_radius=sp.sympify(major) + sp.sympify(minor) * sp.cos(u),
        profile_height=sp.sympify(minor) * sp.sin(u),
    )


def paraboloid_surface(scale: sp.Expr | float | None = None) -> SurfaceOfRevolution:
    u = sp.Symbol("u", positive=True)
    phi = sp.Symbol("phi", real=True)
    a = sp.Symbol("a", positive=True) if scale is None else scale
    return SurfaceOfRevolution(
        family="paraboloid",
        meridian=u,
        azimuth=phi,
        profile_radius=u,
        profile_height=sp.sympify(a) * u**2,
    )


def cone_surface(slope: sp.Expr | float | None = None) -> SurfaceOfRevolution:
    u = sp.Symbol("u", positive=True)
    phi = sp.Symbol("phi", real=True)
    c = sp.Symbol("c", positive=True) if slope is None else slope
    return SurfaceOfRevolution(
        family="cone",
        meridian=u,
        azimuth=phi,
        profile_radius=u,
        profile_height=sp.sympify(c) * u,
    )


def hyperboloid_surface(
    waist_radius: sp.Expr | float | None = None,
    height_scale: sp.Expr | float | None = None,
) -> SurfaceOfRevolution:
    u = sp.Symbol("u", real=True)
    phi = sp.Symbol("phi", real=True)
    a = sp.Symbol("a", positive=True) if waist_radius is None else waist_radius
    c = sp.Symbol("c", positive=True) if height_scale is None else height_scale
    return SurfaceOfRevolution(
        family="hyperboloid",
        meridian=u,
        azimuth=phi,
        profile_radius=sp.sympify(a) * sp.cosh(u),
        profile_height=sp.sympify(c) * sp.sinh(u),
    )


def surface_by_family(family: SurfaceFamily) -> SurfaceOfRevolution:
    if family == "sphere":
        return sphere_surface()
    if family == "torus":
        return torus_surface()
    if family == "paraboloid":
        return paraboloid_surface()
    if family == "cone":
        return cone_surface()
    if family == "hyperboloid":
        return hyperboloid_surface()
    raise ValueError(f"unknown surface family: {family!r}")


def build_system(family: SurfaceFamily = "torus") -> FirstOrderSystem:
    """Return the geodesic flow on a surface of revolution."""

    return surface_by_family(family).geodesic_system()


system = build_system()


__all__ = [
    "SurfaceFamily",
    "SurfaceOfRevolution",
    "build_system",
    "cone_surface",
    "hyperboloid_surface",
    "paraboloid_surface",
    "sphere_surface",
    "surface_by_family",
    "torus_surface",
]
